- name: Zookeeper | Executar ação
  ansible.builtin.systemd:
    name: zookeeper
    state: "{{ zk_state }}"
  when: service_action in ['start','stop','restart']

- name: Zookeeper | Status
  ansible.builtin.systemd:
    name: zookeeper
  register: zk_status

- name: Zookeeper | Exibir status
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} | zookeeper | active={{ zk_status.status.ActiveState | default('n/a') }}"
