- name: Atualizar todos os pacotes
  hosts: all
  become: yes
  tasks:
    - name: Exibir fatos do sistema
      debug:
        var: ansible_facts

    - name: Atualizar todos os pacotes do sistema
      dnf:
        name: "*"
        state: latest

