---
# 1) Validação (uma vez)
- name: Validar survey (run_once)
  hosts: all
  gather_facts: false
  tasks:
    - name: Validar variáveis do survey
      ansible.builtin.assert:
        that:
          - service_action in ['status','start','stop','restart']
          - service_target in ['kafka','zookeeper','both']
        fail_msg: "Survey inválido: service_action={{ service_action }}, service_target={{ service_target }}"
      run_once: true

# 2) START/RESTART -> Zookeeper primeiro
- name: Zookeeper primeiro (start/restart)
  hosts: zookeeper_nodes
  become: true
  gather_facts: false
  roles:
    - role: zookeeper_service
      when:
        - service_target in ['zookeeper','both']
        - service_action in ['start','restart','status']

# 3) START/RESTART -> Kafka depois
- name: Kafka depois (start/restart)
  hosts: kafka_brokers
  become: true
  gather_facts: false
  roles:
    - role: kafka_service
      when:
        - service_target in ['kafka','both']
        - service_action in ['start','restart','status']

# 4) STOP -> Kafka primeiro
- name: Kafka primeiro (stop)
  hosts: kafka_brokers
  become: true
  gather_facts: false
  roles:
    - role: kafka_service
      when:
        - service_target in ['kafka','both']
        - service_action == 'stop'

# 5) STOP -> Zookeeper por último
- name: Zookeeper por último (stop)
  hosts: zookeeper_nodes
  become: true
  gather_facts: false
  roles:
    - role: zookeeper_service
      when:
        - service_target in ['zookeeper','both']
        - service_action == 'stop'
