---
- name: EEF connectivity test
  hosts: localhost
  gather_facts: false

  vars:
    builder_host: "{{ builder_host_input | default('192.168.15.20') }}"

  tasks:
    - name: Show selected builder host
      ansible.builtin.debug:
        msg:
          - "builder_host={{ builder_host }}"

    - name: Test whoami on builder host
      ansible.builtin.command:
        cmd: whoami
      register: whoami_result
      delegate_to: "{{ builder_host }}"

    - name: Show whoami result
      ansible.builtin.debug:
        var: whoami_result.stdout_lines

    - name: Test hostname on builder host
      ansible.builtin.command:
        cmd: hostname
      register: hostname_result
      delegate_to: "{{ builder_host }}"

    - name: Show hostname result
      ansible.builtin.debug:
        var: hostname_result.stdout_lines

    - name: Test podman version on builder host
      ansible.builtin.command:
        cmd: podman --version
      register: podman_result
      delegate_to: "{{ builder_host }}"

    - name: Show podman version
      ansible.builtin.debug:
        var: podman_result.stdout_lines

    - name: Test ansible-builder version on builder host
      ansible.builtin.command:
        cmd: ansible-builder --version
      register: ansible_builder_result
      delegate_to: "{{ builder_host }}"

    - name: Show ansible-builder version
      ansible.builtin.debug:
        var: ansible_builder_result.stdout_lines

    - name: Test git version on builder host
      ansible.builtin.command:
        cmd: git --version
      register: git_result
      delegate_to: "{{ builder_host }}"

    - name: Show git version
      ansible.builtin.debug:
        var: git_result.stdout_lines
