- name: Kafka | Executar ação
  ansible.builtin.systemd:
    name: kafka
    state: "{{ kafka_state }}"
  when: service_action in ['start','stop','restart']

- name: Kafka | Status
  ansible.builtin.systemd:
    name: kafka
  register: k_status

- name: Kafka | Exibir status
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} | kafka | active={{ k_status.status.ActiveState | default('n/a') }}"
